

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

# Restore packages
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    noCache: true

# Add package dependency checks here
- task: DotNetCoreCLI@2
  displayName: 'Check Package Dependencies'
  inputs:
    command: custom
    custom: list
    arguments: 'package --deprecated --vulnerable'
    projects: '$(solution)'
    workingDirectory: '$(Build.SourcesDirectory)'
  continueOnError: true  # Don't fail immediately - just report issues

# Rest of your pipeline continues here...
- task: MSBuild@1
  displayName: 'Generate Binding Redirects'
  inputs:
    solution: '$(solution)'
    msbuildArguments: '/t:GenerateBindingRedirects /p:GenerateBindingRedirectsOutputType=true'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:TargetFramework=net472 /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)" /p:AutoGenerateBindingRedirects=true'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    vsVersion: '16.0'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testRunTitle: 'NET472 Tests'
    vsTestVersion: '16.0'