variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # Add explicit .NET Framework version variable
  targetFramework: 'net472'  # .NET Framework 4.7.2 identifier

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    # Add explicit framework targeting
    msbuildArgs: '/p:TargetFramework=$(targetFramework) /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    # Add framework targeting for tests
    testRunTitle: 'Test $(targetFramework)'
    arguments: '--framework $(targetFramework)'